### ISSUE TITLE
Feature Request: Amazon Redshift

### ISSUE THREAD

**Issue by RAbraham** [mozafari/verdict#53]
Hi,
I am super excited to try out AQP. You mention support for Amazon Redshift coming out soon. I was just curious to know if it is still in your roadmap and when I should circle back to try it out. 

Thanks,
Rajiv

**Comment by pyongjoo** [comment]
Hi Rajiv,

Thanks for asking the question! We are currently adding/testing a driver for Spark SQL (our first customer is using Spark). Next, we will check Druid (since there was a request for it too), and we will work on Redshift since you asked for it :-). Can you check again in a month for the update? But, we will also give updates if we have any related news.

Thanks!
Young

**Comment by pyongjoo** [comment]
Hi Rajiv,

I just had a conversation with my supervisor. It seems like we might be able to release our RedShift driver immediately after this upcoming release. However, we would need to better understand the use-cases that you or other Redshift users might have so we can prioritize which features to add first. 

Do you want to jump on a quick Skype/hangout call sometime this week to discuss what features you might need more urgently? Please send me an email to pyongjoo AT umich.edu.

Thanks,
Young

**Comment by RAbraham** [comment]
Hi Young,
That sounds great. How about next week July 6th, 2 pm EDT?

**Comment by pyongjoo** [comment]
Update 1.

We are currently working on adding a driver for Amazon Redshift. For now, Verdict will connect to Amazon Redshift using the JDBC interface, which seems to be the most common interface to Redshift.

Redshift does not provide a command line interface by default, but Verdict's users will be able to connect to Verdict-on-Redshift using the `veeline` command line interface offered by Verdict. Of course, other front-end applications that allow custom JDBC connections (such as Apache Zeppelin or Python Jupyter) will be able to connect to Verdict-on-Redshift, as possible for the other database systems such as Impala or Hive.

**Comment by RAbraham** [comment]
Reg: Redshift not providing a command line interface, you may already know about it but we use the standard `psql ` command line interface of PostgreSQL for interacting with Redshift as Redshift is based on PostgreSQL 8.0.2. 

No issues so far :)
