### ISSUE TITLE
Equations Documentation

### ISSUE THREAD

**Issue by Mwea** [mozafari/verdict#88]
Hi ! 

I found your paper : 
https://web.eecs.umich.edu/~mozafari/php/data/uploads/sigmod_2017_dbl.pdf

And thought that it could be really interesting to look at your implementation, sadly I didn't manage to find any code related to the equation you're speaking about in the section 5.  Specially the computing part of the covariance and mean. 

Is there any info I missed in your project ? 

It could be really great if there was some documentation in your code refering to sections/equations of your paper 👍 

Thank you for all !

**Comment by pyongjoo** [comment]
Hi. Thanks for the question. Right now, this repository does not include the database learning implementation we used for the paper, but we will certainly include it in the future.

**Comment by Mwea** [comment]
Ho, my bad ! 

So.. What does include this repository ? I thought that this was an implementation. 

How do you actually predict aggregate queries without your covariance matrix ? 

I'm thinking about working on a basic implementation of your paper.

**Comment by pyongjoo** [comment]
I'm sorry for causing your confusion. For clarification, the current repository is about how to turn your regular database systems into an AQP system without making any modifications to the regular database system.

The database learning paper, which will also be added to this repository in the future, talks about how to further boost the performance of AQP systems by building probabilistic models (covariance matrices are part of them) and using those models for refining inaccurate AQP answers.
