### ISSUE TITLE
Request: Create Google Group(vs verdict-user@umich.edu)?

### ISSUE THREAD

**Issue by RAbraham** [mozafari/verdict#90]
Hi,
When I try to access the Verdict User group(with my Friend Account), I get an `Access Denied` error. I was wondering if it would make sense to create a Google Group/Slack/Gitter for verdict? It's easier to access.

I have some general questions which are not `issues` and hence not relevant to the Issues tab in Github.

**Comment by pyongjoo** [comment]
Thanks for creating a Google group: https://groups.google.com/forum/#!forum/verdict

I also have updated the official Verdict website: http://verdictdb.org/community/
