### ISSUE TITLE
Error: Could not find or load main class sqlline.SqlLine

### ISSUE THREAD

**Issue by RAbraham** [mozafari/verdict#91]
Hi,
When I run,
``` bash
veeline/bin/veeline -h "redshift://my_redshift_cluster:my_port/my_db" -u myuser -p my_pwd
```
I get the error
``` bash
veeline/bin/../../jars/verdict-jdbc-0.3.0-snapshot-jar-with-dependencies.jar:veeline/bin/../../jars/verdict-veeline-0.3.0-snapshot-jar-with-dependencies.jar
Error: Could not find or load main class sqlline.SqlLine
```

or 
``` bash
bin/verdict-shell -h "redshift://my_redshift_cluster:my_port/my_db" -u myuser -p my_pwd
```
then just
```
Error: Could not find or load main class sqlline.SqlLine
```

I pulled the latest repo and did `mvn clean package`

**Comment by pyongjoo** [comment]
Hi Rajiv,

I apologize for the error. I just wanted to let you know that, right now, we are slow in fixing these bugs due to an upcoming paper deadline. I'll get back to this issue as soon as I finish other tasks.

Regards,
Yongjoo

**Comment by RAbraham** [comment]
No problem, best of luck for the paper and looking forward to seeing it one day!

**Comment by dongyoungy** [comment]
Closing this issue since OP has not been responding.

**Comment by RAbraham** [comment]
I apologize! I totally missed this. Unfortunately, I have been pulled on to a separate project and can't dedicate time to this right now. I hope to come back to it when things settle down.

**Comment by dongyoungy** [comment]
That's completely okay. Please feel free to come back later and let us know after things are settled with you. We will reopen this issue if necessary.
