### ISSUE TITLE
Will the samples get updated if the base table is changed?

### ISSUE THREAD

**Issue by xuebinsu** [mozafari/verdict#96]

**Comment by pyongjoo** [comment]
Yes and no. Our current target is supporting data append (not in-place updates), which is the most common type of table update operations in HDFS-based database systems.

**Comment by pyongjoo** [comment]
In addition, any changes that occurred to base tables could be automatically detected by checking the latest timestamp when underlying HDFS files are modified. Right now, this public repo does not support that feature. I have added this feature to this issue: https://github.com/mozafari/verdict/issues/95

**Comment by xuebinsu** [comment]
Thanks for explanation!
